import { RxDashboard } from "react-icons/rx";
import { FiUsers } from "react-icons/fi";
import { MdOutlineSettingsInputComposite } from "react-icons/md";
import { FaCalendar } from "react-icons/fa";
import { FaRegMessage } from "react-icons/fa6";
import { CiBadgeDollar } from "react-icons/ci";
import { GoGraph } from "react-icons/go";
import { LuHistory } from "react-icons/lu";
import { LuBuilding2 } from "react-icons/lu";
import { FaBed } from "react-icons/fa";
import { IoMdBook } from "react-icons/io";
import { SlGraph } from "react-icons/sl";
import { PiStarFourBold } from "react-icons/pi";
import { FiMoon } from "react-icons/fi";
import { IoIosSunny } from "react-icons/io";
import { CiSettings } from "react-icons/ci";
import { FaRegStar } from "react-icons/fa";
// 
import { LuMessageSquareMore } from "react-icons/lu";
import { IoMdTime } from "react-icons/io";
import { MdOutlinePhoneInTalk } from "react-icons/md";
import { MdOutlineVerifiedUser } from "react-icons/md";
import { BsGraphUpArrow } from "react-icons/bs";
import { CiStopwatch, CiWarning } from "react-icons/ci";
import { TiArrowUp, TiArrowDown } from "react-icons/ti";
import { FaMoneyCheckDollar } from "react-icons/fa6";

import { MdOutlineCurrencyRupee } from "react-icons/md";
import { CiCircleCheck } from "react-icons/ci";
 export const links=[
 {id:1,link:'/',title:'dasboard',icons:RxDashboard},
 {id:2,link:'/leads',title:'leads',icons:FiUsers},
 {id:3,link:'/pipeline',title:'pipeline',icons:MdOutlineSettingsInputComposite},
 {id:4,link:'/visits',title:'visits',icons:FaCalendar},
 {id:5,link:'/messages',title:'messages',icons:FaRegMessage},
 {id:6,link:'/bookings',title:'bookings',icons:CiBadgeDollar},
 {id:7,link:'/analytics',title:'analytics',icons:GoGraph},
 {id:8,link:'/historical',title:'historical',icons:LuHistory},
 {id:9,link:'/owners',title:'owners',icons:LuBuilding2},
 {id:10,link:'/inventory',title:'inventory',icons:FaBed},
 {id:11,link:'/availability',title:'availability',icons:IoMdBook},
//  {id:12,link:'/effort',title:'effort',icons:SlGraph},
//  {id:13,link:'/matching',title:'matching',icons:PiStarFourBold},
 {id:12,link:'/settings',title:'settings',icons:CiSettings},

]




export const data_dash = [
  {
    id: 1,
    icon: FiUsers,
    value: 14,
    title: "Total Leads",
    percentage: "12%",
    trend: "up",
    iconBg: "bg-pink-100",
    iconColor: "text-yellow-500",
  },
  {
    id: 2,
    icon: IoMdTime,
    value: "5h",
    title: "Response Time",
    percentage: "8%",
    trend: "down",
    iconBg: "bg-blue-100",
    iconColor: "text-blue-500",
  },
  {
    id: 3,
    icon: FaCalendar,
    value: 25,
    title: "Visits",
    percentage: "18%",
    trend: "up",
    iconBg: "bg-green-100",
    iconColor: "text-green-500",
  },
  {
    id: 4,
    icon: MdOutlineVerifiedUser,
    value: 10,
    title: "Verified Users",
    percentage: "5%",
    trend: "up",
    iconBg: "bg-purple-100",
    iconColor: "text-purple-500",
  },
  {
    id: 5,
    icon: BsGraphUpArrow,
    value: "84%",
    title: "Conversion Rate",
    percentage: "10%",
    trend: "up",
    iconBg: "bg-orange-100",
    iconColor: "text-orange-500",
  },
  {
    id: 6,
    icon: CiStopwatch,
    value: "2m",
    title: "Avg. Time",
    percentage: "3%",
    trend: "down",
    iconBg: "bg-cyan-100",
    iconColor: "text-cyan-500",
  },
  {
    id: 7,
    icon: FiUsers,
    value: 50,
    title: "Customers",
    percentage: "15%",
    trend: "up",
    iconBg: "bg-indigo-100",
    iconColor: "text-indigo-500",
  },
  {
    id: 8,
    icon: CiWarning,
    value: 2,
    title: "Warnings",
    percentage: "4%",
    trend: "down",
    iconBg: "bg-red-100",
    iconColor: "text-red-500",
  },
];

export const needs=[
 {id:1,rent:'rs- 7,500-1000',name:'amit saxena',client:'rahul verma',wait:'awaiting'},
 {id:2,rent:'rs- 8,500-1100',name:'nikhil agarwal',client:'anita desal',wait:'awaiting'},
 {id:3,rent:'rs- 9,500-1200',name:'aarav patel',client:'priya sharma',wait:'awaiting'},
]
export const hot_leads=[
 {id:1,name:'divya nair',location:'indirangar',rating:70,icons:FaRegStar },
 {id:2,name:'suresh lyer',location:'whitefield',rating:90,icons:FaRegStar },
 {id:3,name:'rohit sharma',location:'marathahalli',rating:40,icons:FaRegStar },
 {id:4,name:'arjun kapoor',location:'electronic city',rating:200,icons:FaRegStar },
 {id:5,name:'sham ',location:'model store',rating:100,icons:FaRegStar },
]
export const agent_performance=[
 {id:1,name:'divya nair',percent:'0%',active:'4active',avg:'3.7 avg',booked:'0',conversion:'conversion' },
 {id:2,name:'suresh lyer',percent:'0%',active:'4active',avg:'3.7 avg',booked:'0',conversion:'conversion' },
 {id:3,name:'rohit sharma',percent:'0%',active:'4active',avg:'3.7 avg',booked:'0',conversion:'conversion' },
 {id:4,name:'arjun kapoor',percent:'33%',active:'4active',avg:'3.7 avg',booked:'0',conversion:'conversion' },
 {id:5,name:'sham ',percent:'0%',active:'4active',avg:'3.7 avg',booked:'0',conversion:'conversion' },
]
 

  export const nav_dashboard_data = [
  {
    id: 1,
    heading: "All Leads",
    explain: "14 leads found",
    link:'All Leads'
  },
  {
    id: 2,
    heading: "Pipeline",
    explain: "Revenue engine - track leads through every stage",
    link:'pipeline'
  },
  {
    id: 3,
    heading: "Visits",
    explain: "Manage property visits and track outcomes",
    link:'visits'
  },
  {
    id: 4,
    heading: "Conversations",
    explain: "WhatsApp & messaging hub",
link:'messages'
  },
  {
    id: 5,
    heading: "Bookings",
    explain: "Manage bookings, payments, and revenue tracking",
link:'bookings'
  },
  {
    id: 6,
    heading: "Analytics",
    explain: "Performance metrics and insights"
,link:'analytics'
  },
  {
    id: 7,
    heading: "Historical Leads",
    explain: "Import and re-engage past leads"
,link:'historical'
  },
  {
    id: 8,
    heading: "Owners",
    explain: "Manage property owners and their portfolios",
    link:'owners'
  },
  {
    id: 9,
    heading: "Room",
    explain: "Inventory - real-time room availability"
,link:'room'
  },
  {
    id: 10,
    heading: "Availability",
    explain: "Sales intelligence - what to pitch right now",
link:'availability'
  },
  {
    id: 11,
    heading: "Effort Visibility",
    explain: "Transparent effort metrics per property",
link:'effort'
  },
  {
    id: 12,
    heading: "Lead Room Matching",
    explain: "AI-powered inventory recommendations for each lead",
link:'matching'
  },
  {
    id: 13,
    heading: "Settings",
    explain: "System configuration",
link:'settings'
  }
];


export const lead_user = [
  {
    id: 1,
    name: "sham",
    contact: "9846787635",
    source: "phone call",
    status: "new lead",
    score: 14,
    agent: "rahul verma",
    location: "HSR Layout",
    actions_phone: MdOutlinePhoneInTalk,
    actions_message: LuMessageSquareMore,
  },
  {
    id: 2,
    name: "ram",
    contact: "8467897635",
    source: "whatsapp",
    status: "contacted",
    score: 16,
    agent: "anita desal",
    location: "jp nagar",
    actions_phone: MdOutlinePhoneInTalk,
    actions_message: LuMessageSquareMore,
  },
  {
    id: 3,
    name: "gaurav",
    contact: "9926787635",
    source: "instagram",
    status: "booked",
    score: 19,
    agent: "priya",
    location: "model 10",
    actions_phone: MdOutlinePhoneInTalk,
    actions_message: LuMessageSquareMore,
  },
  {
    id: 4,
    name: "geeta",
    contact: "8367287635",
    source: "phone call",
    status: "new lead",
    score: 13,
    agent: "priya sharma",
    location: "new park first shop",
    actions_phone: MdOutlinePhoneInTalk,
    actions_message: LuMessageSquareMore,
  },
  {
    id: 5,
    name: "peter",
    contact: "78246787635",
    source: "facebook",
    status: "contacted",
    score: 14,
    agent: "vijay",
    location: "koramangala",
    actions_phone: MdOutlinePhoneInTalk,
    actions_message: LuMessageSquareMore,
  },
  {
    id: 6,
    name: "john",
    contact: "8846787635",
    source: "landing page",
    status: "booked",
    score: 15,
    agent: "anita desals",
    location: "btm layout",
    actions_phone: MdOutlinePhoneInTalk,
    actions_message: LuMessageSquareMore,
  },
 {
  id: 7,
  name: "rohit",
  contact: "9876543210",
  source: "website",
  status: "new lead",
  score: 12,
  agent: "amit saxena",
  location: "whitefield",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 8,
  name: "neha",
  contact: "9123456780",
  source: "facebook",
  status: "contacted",
  score: 18,
  agent: "priya",
  location: "electronic city",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 9,
  name: "vikas",
  contact: "9988776655",
  source: "instagram",
  status: "booked",
  score: 20,
  agent: "rahul verma",
  location: "marathahalli",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 10,
  name: "sneha",
  contact: "8877665544",
  source: "whatsapp",
  status: "contacted",
  score: 17,
  agent: "anita desal",
  location: "jayanagar",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 11,
  name: "karan",
  contact: "7766554433",
  source: "phone call",
  status: "new lead",
  score: 11,
  agent: "vijay",
  location: "hebbal",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 12,
  name: "pooja",
  contact: "6655443322",
  source: "landing page",
  status: "booked",
  score: 21,
  agent: "priya sharma",
  location: "banashankari",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 13,
  name: "arjun",
  contact: "9543218765",
  source: "website",
  status: "new lead",
  score: 15,
  agent: "amit saxena",
  location: "indiranagar",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 14,
  name: "meera",
  contact: "8765432190",
  source: "facebook",
  status: "contacted",
  score: 16,
  agent: "rahul verma",
  location: "rajajinagar",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
},
{
  id: 15,
  name: "akash",
  contact: "7894561230",
  source: "instagram",
  status: "booked",
  score: 22,
  agent: "anita desal",
  location: "bellandur",
  actions_phone: MdOutlinePhoneInTalk,
  actions_message: LuMessageSquareMore,
}
];
export const pipeline = [
  {
    id: 1,
    stale: "new",
    name: "Amit Sharma",
    mobile: "9876543210",
    score: 'phone call',
    location: "Delhi",
    rent: "₹15,000",
    agent: "Rahul Verma",
  },
  {
    id: 2,
    stale: "contacted",
    name: "Priya Singh",
    mobile: "9876543211",
    score: 'phone call',
    location: "Noida",
    rent: "₹18,000",
    agent: "Ankit Kumar",
  },
  {
    id: 3,
    stale: "qualified",
    name: "Rohit Kumar",
    mobile: "9876543212",
    score: 'whatapp',
    location: "Gurgaon",
    rent: "₹25,000",
    agent: "Neha Gupta",
  },
  {
    id: 4,
    stale: "follow up",
    name: "Simran Kaur",
    mobile: "9876543213",
    score: 'instagram',
    location: "Chandigarh",
    rent: "₹12,000",
    agent: "Rahul Verma",
  },
  {
    id: 5,
    stale: "proposal",
    name: "Arjun Mehta",
    mobile: "9876543214",
    score: 'whatapp',
    location: "Mohali",
    rent: "₹20,000",
    agent: "Ankit Kumar",
  },
  {
    id: 6,
    stale: "negotiation",
    name: "Karan Malhotra",
    mobile: "9876543215",
    score: 'phone call',
    location: "Ludhiana",
    rent: "₹30,000",
    agent: "Neha Gupta",
  },
  {
    id: 7,
    stale: "closed",
    name: "Pooja Arora",
    mobile: "9876543216",
    score: 'whatapp',
    location: "Jalandhar",
    rent: "₹22,000",
    agent: "Rahul Verma",
  },
];

export const visit = [
  {
    id: 1,
    name: "Divya Nair",
    location: "HomePay Residency, Indiranagar",
    conform: "Confirm",
    time: "Mar 11, 8:58 PM",
    manager: "Priya",
    booking: "Booked",
    considered: "Considering",
    not_interested: "Not Interested",
  },
  {
    id: 2,
    name: "Rahul Sharma",
    location: "Green Valley Apartments, Whitefield",
    conform: "Confirm",
    time: "Mar 12, 10:30 AM",
    manager: "Priya",
    booking: "Booked",
    considered: "Considering",
    not_interested: "Not Interested",
  },
  {
    id: 3,
    name: "Anjali Verma",
    location: "Skyline Towers, Koramangala",
    conform: "Confirm",
    time: "Mar 12, 2:15 PM",
    manager: "Priya",
    booking: "Booked",
    considered: "Considering",
    not_interested: "Not Interested",
  },
  {
    id: 4,
    name: "Karan Singh",
    location: "Prestige Lakeside Habitat, Varthur",
    conform: "Confirm",
    time: "Mar 13, 11:45 AM",
    manager: "Priya",
    booking: "Booked",
    considered: "Considering",
    not_interested: "Not Interested",
  },
  {
    id: 5,
    name: "Sneha Reddy",
    location: "Brigade Metropolis, Mahadevapura",
    conform: "Confirm",
    time: "Mar 13, 5:20 PM",
    manager: "TBD",
    booking: "Booked",
    considered: "Considering",
    not_interested: "Not Interested",
  },
];
export const complete_visite = [
  {
    id: 1,
    name: "Karan Singh",
    property: "Prestige Lakeside Habitat, Varthur",
    conform: "Confirm",
    time: "Mar 13, 11:45 AM",
    staff: "Priya",
    outcomes:'considering'
  },
  {
    id: 2,
    name: "Rahul Sharma",
    property: "Brigade Cornerstone Utopia, Whitefield",
    conform: "Confirm",
    time: "Mar 14, 02:15 PM",
    staff: "Anjali",
    outcomes:'considering'
  },
  {
    id: 3,
    name: "Neha Gupta",
    property: "Sobha Dream Acres, Panathur",
    conform: "Confirm",
    time: "Mar 15, 10:30 AM",
    staff: "Ritika",
    outcomes:'considering'
  },
  {
    id: 4,
    name: "Amit Verma",
    property: "Godrej Air NXT, Hoodi",
    conform: "Confirm",
    time: "Mar 16, 04:00 PM",
    staff: "Rohan",
    outcomes:'considering'
  },
  {
    id: 5,
    name: "Pooja Nair",
    property: "Assetz Marq, Whitefield",
    conform: "Confirm",
    time: "Mar 17, 12:20 PM",
    staff: "Priya",
    outcomes:'considering'
  },
];
export const bookings=[
  {id:1,results:'total bookings',booking_type:'0',icons:FaMoneyCheckDollar},
  {id:2,results:'pending',booking_type:'0',icons:CiCircleCheck},
  {id:3,results:'confirmed',booking_type:'0',icons:IoMdTime},
  {id:4,results:'monthly revenue',booking_type:'0-k',icons:BsGraphUpArrow },
  {id:5,results:'pipeline revenue',booking_type:'0-k',icons:MdOutlineCurrencyRupee},

] 
export const history_data = [
  {
    id: 1,
    name: "Pooja Gupta",
    phone: "+91 21098 76543",
    source: "Website",
    status: "lost",
    location: "Yelahanka",
    created: "Feb 25, 2026",
  },
  {
    id: 2,
    name: "Arjun Kapoor",
    phone: "+91 32109 87654",
    source: "WhatsApp",
    status: "booked",
    location: "Electronic City",
    created: "Feb 28, 2026",
  },
  {
    id: 3,
    name: "Meera Joshi",
    phone: "+91 43210 98765",
    source: "Landing Page",
    status: "visit completed",
    location: "Whitefield",
    created: "Mar 3, 2026",
  },
  {
    id: 4,
    name: "Rohit Kumar",
    phone: "+91 54321 09876",
    source: "Phone Call",
    status: "visit scheduled",
    location: "Marathahalli",
    created: "Mar 5, 2026",
  },
  {
    id: 5,
    name: "Kavita Rao",
    phone: "+91 54312 34567",
    source: "Facebook",
    status: "property suggested",
    location: "BTM Layout",
    created: "Mar 5, 2026",
  },
  {
    id: 6,
    name: "Divya Nair",
    phone: "+91 65432 10987",
    source: "Facebook",
    status: "property suggested",
    location: "Indiranagar",
    created: "Mar 6, 2026",
  },
  {
    id: 7,
    name: "Suresh Iyer",
    phone: "+91 65412 34567",
    source: "Website",
    status: "visit scheduled",
    location: "Whitefield",
    created: "Mar 6, 2026",
  },
  {
    id: 8,
    name: "Karan Mehta",
    phone: "+91 76543 21098",
    source: "Instagram",
    status: "requirement collected",
    location: "BTM Layout",
    created: "Mar 7, 2026",
  },
  {
    id: 9,
    name: "Tanvi Shah",
    phone: "+91 76512 34567",
    source: "Landing Page",
    status: "requirement collected",
    location: "Indiranagar",
    created: "Mar 7, 2026",
  },
  {
    id: 10,
    name: "Riya Chatterjee",
    phone: "+91 98712 34567",
    source: "Instagram",
    status: "contacted",
    location: "Koramangala",
    created: "Mar 8, 2026",
  },
  {
    id: 11,
    name: "Sneha Reddy",
    phone: "+91 87654 32109",
    source: "Website",
    status: "contacted",
    location: "HSR Layout",
    created: "Mar 8, 2026",
  },
  {
    id: 12,
    name: "Aarav Patel",
    phone: "+91 98765 43210",
    source: "WhatsApp",
    status: "new",
    location: "Koramangala",
    created: "Mar 8, 2026",
  },
  {
    id: 13,
    name: "Nikhil Agarwal",
    phone: "+91 10987 65432",
    source: "WhatsApp",
    status: "new",
    location: "JP Nagar",
    created: "Mar 8, 2026",
  },
  {
    id: 14,
    name: "Amit Saxena",
    phone: "+91 87612 34567",
    source: "Phone Call",
    status: "new",
    location: "HSR Layout",
    created: "Mar 8, 2026",
  },
];
 export const owners = [
  {
    id: 1,
    name: "Sss",
    email: "sssss@gmail.com",
    status: "Active",
    properties: 0,
    phone:'8653788384738'
  },
  {
    id: 2,
    name: "Rahul Sharma",
    email: "rahul@gmail.com",
    status: "Active",
    properties: 3,
    phone:'8653788384738'
  },
  {
    id: 3,
    name: "Priya Singh",
    email: "priya@gmail.com",
    status: "Inactive",
    properties: 1,
    phone:'8653788384738'
  },
  {
    id: 4,
    name: "Amit Kumar",
    email: "amit@gmail.com",
    status: "Active",
    properties: 5,
    phone:'8653788384738'
  },
  {
    id: 5,
    name: "Neha Gupta",
    email: "neha@gmail.com",
    status: "Pending",
    properties: 2,
    phone:'8883847380'
  },
  {
    id: 6,
    name: "Rohit Verma",
    email: "rohit@gmail.com",
    status: "Active",
    properties: 4,
    phone:'8688384738'
  },
  {
    id: 7,
    name: "Sneha Patel",
    email: "sneha@gmail.com",
    status: "Inactive",
    properties: 0,
    phone:'7883847384'
  },
  {
    id: 8,
    name: "Vikram Joshi",
    email: "vikram@gmail.com",
    status: "Active",
    properties: 6,
    phone:'vvk'
  },
  {
    id: 9,
    name: "Anjali Mehta",
    email: "anjali@gmail.com",
    status: "Pending",
    properties: 1,
     phone:'ann'
  },
  {
    id: 10,
    name: "Karan Malhotra",
    email: "karan@gmail.com",
    status: "Active",
    properties: 7,
    phone:'8653788384738'
  },
];
export const inventory = [
  {
    id: 1,
    room: "Room 4555",
    property: "Comfort Zone PG",
    owner: "Vikram Patel",
    status: "Vacant",
    beds: 1,
    type: "Single",
    ask: 54566,
    confirmed: "7 days ago",
  },
  {
    id: 2,
    room: "Room 2101",
    property: "Sunrise Residency",
    owner: "Rahul Sharma",
    status: "Occupied",
    beds: 2,
    type: "Double",
    ask: 18500,
    confirmed: "2 days ago",
  },
  {
    id: 3,
    room: "Room 3304",
    property: "City Nest PG",
    owner: "Priya Singh",
    status: "Vacant",
    beds: 1,
    type: "Single",
    ask: 15000,
    confirmed: "5 days ago",
  },
  {
    id: 4,
    room: "Room 1208",
    property: "Green Valley PG",
    owner: "Amit Kumar",
    status: "Occupied",
    beds: 3,
    type: "Triple",
    ask: 12000,
    confirmed: "1 week ago",
  },
  {
    id: 5,
    room: "Room 4502",
    property: "Royal Stay PG",
    owner: "Neha Gupta",
    status: "Vacant",
    beds: 2,
    type: "Double",
    ask: 17500,
    confirmed: "3 days ago",
  },
  {
    id: 6,
    room: "Room 5106",
    property: "Urban Living PG",
    owner: "Rohit Verma",
    status: "Occupied",
    beds: 1,
    type: "Single",
    ask: 21000,
    confirmed: "10 days ago",
  },
  {
    id: 7,
    room: "Room 3009",
    property: "Blue Sky PG",
    owner: "Sneha Patel",
    status: "Vacant",
    beds: 2,
    type: "Double",
    ask: 16000,
    confirmed: "4 days ago",
  },
  {
    id: 8,
    room: "Room 6102",
    property: "Happy Homes PG",
    owner: "Karan Malhotra",
    status: "Occupied",
    beds: 1,
    type: "Single",
    ask: 22000,
    confirmed: "12 days ago",
  },
  {
    id: 9,
    room: "Room 7101",
    property: "Elite Residency",
    owner: "Anjali Mehta",
    status: "Vacant",
    beds: 3,
    type: "Triple",
    ask: 13500,
    confirmed: "6 days ago",
  },
  {
    id: 10,
    room: "Room 2505",
    property: "Metro PG",
    owner: "Deepak Arora",
    status: "Occupied",
    beds: 2,
    type: "Double",
    ask: 17000,
    confirmed: "8 days ago",
  },
  {
    id: 11,
    room: "Room 4203",
    property: "Dream Stay PG",
    owner: "Pooja Jain",
    status: "Vacant",
    beds: 1,
    type: "Single",
    ask: 14500,
    confirmed: "2 weeks ago",
  },
  {
    id: 12,
    room: "Room 5508",
    property: "Golden Nest PG",
    owner: "Arjun Kapoor",
    status: "Occupied",
    beds: 2,
    type: "Double",
    ask: 19500,
    confirmed: "9 days ago",
  },
  {
    id: 13,
    room: "Room 1802",
    property: "Comfort Plus PG",
    owner: "Meera Nair",
    status: "Vacant",
    beds: 1,
    type: "Single",
    ask: 15500,
    confirmed: "11 days ago",
  },
  {
    id: 14,
    room: "Room 6704",
    property: "Skyline PG",
    owner: "Vikas Yadav",
    status: "Occupied",
    beds: 4,
    type: "Dormitory",
    ask: 10000,
    confirmed: "5 days ago",
  },
  {
    id: 15,
    room: "Room 2907",
    property: "Silver Residency",
    owner: "Ritika Sharma",
    status: "Vacant",
    beds: 2,
    type: "Double",
    ask: 18000,
    confirmed: "1 day ago",
  },
  {
    id: 16,
    room: "Room 3501",
    property: "Smart Living PG",
    owner: "Nitin Bansal",
    status: "Occupied",
    beds: 1,
    type: "Single",
    ask: 20500,
    confirmed: "13 days ago",
  },
  {
    id: 17,
    room: "Room 4706",
    property: "Prime Stay PG",
    owner: "Sonal Verma",
    status: "Vacant",
    beds: 3,
    type: "Triple",
    ask: 14000,
    confirmed: "7 days ago",
  },
  {
    id: 18,
    room: "Room 5209",
    property: "Town Square PG",
    owner: "Manish Gupta",
    status: "Occupied",
    beds: 2,
    type: "Double",
    ask: 18500,
    confirmed: "3 days ago",
  },
  {
    id: 19,
    room: "Room 8103",
    property: "Comfort Hub PG",
    owner: "Shreya Kapoor",
    status: "Vacant",
    beds: 1,
    type: "Single",
    ask: 16500,
    confirmed: "15 days ago",
  },
  {
    id: 20,
    room: "Room 9205",
    property: "Modern Nest PG",
    owner: "Akash Singh",
    status: "Occupied",
    beds: 2,
    type: "Double",
    ask: 19000,
    confirmed: "4 days ago",
  },
];
 export const avaiability = [
  {
    id: 1,
    area: "Electronic City",
    vacant: 33,
    properties: [
      {
        name: "CloudNine PG",
        vacantBeds: "23 / 27",
        rentPerBed: 5000,
        nextVacancy: "—",
      },
      {
        name: "Gharpayy Nest - Electronic City",
        vacantBeds: "10 / 10",
        rentPerBed: 5500,
        nextVacancy: "—",
      },
    ],
  },
  {
    id: 2,
    area: "Whitefield",
    vacant: 28,
    properties: [
      {
        name: "TechNest Co-Living",
        vacantBeds: "18 / 21",
        rentPerBed: 8000,
        nextVacancy: "—",
      },
      {
        name: "Gharpayy Villa - Whitefield",
        vacantBeds: "10 / 10",
        rentPerBed: 7000,
        nextVacancy: "—",
      },
    ],
  },
  {
    id: 3,
    area: "Marathahalli",
    vacant: 25,
    properties: [
      {
        name: "Sunrise PG for Men",
        vacantBeds: "15 / 18",
        rentPerBed: 8000,
        nextVacancy: "—",
      },
      {
        name: "Gharpayy Heights - Marathahalli",
        vacantBeds: "10 / 10",
        rentPerBed: 6500,
        nextVacancy: "—",
      },
    ],
  },
  {
    id: 4,
    area: "BTM Layout",
    vacant: 22,
    properties: [
      {
        name: "Comfort Zone PG",
        vacantBeds: "12 / 12",
        rentPerBed: 5500,
        nextVacancy: "—",
      },
      {
        name: "Gharpayy Homes - BTM",
        vacantBeds: "10 / 10",
        rentPerBed: 7000,
        nextVacancy: "—",
      },
    ],
  },
  {
    id: 5,
    area: "Indiranagar",
    vacant: 17,
    properties: [
      {
        name: "Urban Nest Coliving",
        vacantBeds: "11 / 15",
        rentPerBed: 15000,
        nextVacancy: "—",
      },
      {
        name: "Gharpayy Residency - Indiranagar",
        vacantBeds: "6 / 6",
        rentPerBed: 15000,
        nextVacancy: "—",
      },
    ],
  },
  {
    id: 6,
    area: "Sarjapur Road",
    vacant: 17,
    properties: [
      {
        name: "Zenith Co-Living Hub",
        vacantBeds: "17 / 18",
        rentPerBed: 8000,
        nextVacancy: "—",
      },
    ],
  },
  {
    id: 7,
    area: "Koramangala",
    vacant: 14,
    properties: [
      {
        name: "Green Valley PG",
        vacantBeds: "14 / 15",
        rentPerBed: 9500,
        nextVacancy: "—",
      },
    ],
  },
  {
    id: 8,
    area: "Bellandur",
    vacant: 4,
    properties: [
      {
        name: "Lakeview Women's PG",
        vacantBeds: "4 / 18",
        rentPerBed: 9000,
        nextVacancy: "—",
      },
    ],
  },
];
export const team_member=[
  {id:1,name:'anita desai',email:'anita@hompay.com',account:'deactive'},
  {id:2,name:'sham',email:'sham@hompay.com',account:'deactive'},
{id:3,name:'venaa roy',email:'venaa@hompay.com',account:'deactive'},
  {id:4,name:'john smith',email:'john@hompay.com',account:'dective'},
]
export const properties=[
  {id:1,name:'anita desai',el_ci_pr:'electronic city,bangalore-₹1500-₹900'},
  {id:2,name:'sham',el_ci_pr:'BTM layout,bangalore-₹5500-₹1000'},
{id:3,name:'venaa roy',el_ci_pr:'marathalhali,banglore ,bangalore-₹6500-₹12000'},
  {id:4,name:'john smith',el_ci_pr:'electronic city,bangalore-₹1500-₹900'},
]